table Bridge_Title_Genre
	lineageTag: 05a39172-334d-456b-8111-66f7ece3bfbc

	column title_key
		dataType: int64
		formatString: 0
		lineageTag: ed587ed2-37ea-43b6-af59-3385d488b748
		summarizeBy: none
		sourceColumn: title_key

		annotation SummarizationSetBy = Automatic

	column genre_key
		dataType: int64
		formatString: 0
		lineageTag: fe88c4e7-562d-40ab-acfe-e6e7c6cc8ef4
		summarizeBy: none
		sourceColumn: genre_key

		annotation SummarizationSetBy = Automatic

	column genre_weight
		dataType: double
		lineageTag: 53daee06-f352-44ef-9f6d-3611214dcc45
		summarizeBy: sum
		sourceColumn: genre_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Bridge_Title_Genre = m
		mode: import
		queryGroup: Bridge_Tables
		source =
				let
				    SourceJSON = Json.Document(File.Contents(File_Path & "boxoffice_budget_feed.json")),
				    DataJSON = SourceJSON[data],
				    TableJSON = Table.FromList(DataJSON, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    ExpandedJSON = Table.ExpandRecordColumn(TableJSON, "Column1", {"stream_id", "categorization"}, {"netflix_id", "categorization"}),
				    ExpandedCat = Table.ExpandRecordColumn(ExpandedJSON, "categorization", {"genres"}, {"genres_raw"}),
				
				    AddListJSON = Table.AddColumn(ExpandedCat, "Genre_List", each
				        if Value.Is([genres_raw], type list) then [genres_raw]
				        else Text.Split(Text.From([genres_raw]), "|"),
				        type list
				    ),
				    ExpandedRowsJSON = Table.ExpandListColumn(AddListJSON, "Genre_List"),
				    CleanGenreNameJSON = Table.TransformColumns(ExpandedRowsJSON, {{"Genre_List", each Text.Trim(Text.From(_)), type text}}),
				    SelectJSONBridge = Table.SelectColumns(CleanGenreNameJSON, {"netflix_id", "Genre_List"}),
				
				    SourceHist = Csv.Document(File.Contents(File_Path & "netflix_enriched_historical.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHist = Table.PromoteHeaders(SourceHist, [PromoteAllScalars=true]),
				    CleanHistGenres = Table.AddColumn(PromotedHist, "Genre_List", each
				        let
				            raw = Text.Replace(Text.Replace(Text.Replace(Text.From([genres]), "[", ""), "]", ""), "'", ""),
				            items = Text.Split(raw, ";")
				        in
				            List.Transform(items, each Text.Proper(Text.Trim(_))),
				        type list
				    ),
				    ExpandedHistRows = Table.ExpandListColumn(CleanHistGenres, "Genre_List"),
				    RenameHistBridge = Table.RenameColumns(ExpandedHistRows, {{"id", "netflix_id"}}),
				    SelectHistBridge = Table.SelectColumns(RenameHistBridge, {"netflix_id", "Genre_List"}),
				
				    CombinedBridges = Table.Combine({SelectJSONBridge, SelectHistBridge}),
				    FilteredEmpty = Table.SelectRows(CombinedBridges, each [Genre_List] <> "" and [Genre_List] <> null),
				
				    StandardizedGenreName = Table.AddColumn(FilteredEmpty, "genre_name_clean", each
				        let g = if [Genre_List] = null then "" else Text.Proper(Text.From([Genre_List])) in
				        if Text.Contains(g, "Action") then "Action"
				        else if Text.Contains(g, "Adventure") then "Adventure"
				        else if Text.Contains(g, "Animation") or Text.Contains(g, "Anime") then "Animation"
				        else if Text.Contains(g, "Comedy") or Text.Contains(g, "Comedies") then "Comedy"
				        else if Text.Contains(g, "Crime") then "Crime"
				        else if Text.Contains(g, "Docu") then "Documentary"
				        else if Text.Contains(g, "Drama") then "Drama"
				        else if Text.Contains(g, "Family") or Text.Contains(g, "Children") then "Family"
				        else if Text.Contains(g, "Fantasy") then "Fantasy"
				        else if Text.Contains(g, "Horror") then "Horror"
				        else if Text.Contains(g, "Sci") then "Science Fiction"
				        else if Text.Contains(g, "Thrill") then "Thriller"
				        else if Text.Contains(g, "Romance") or Text.Contains(g, "Romantic") then "Romance"
				        else "Drama",
				        type text
				    ),
				
				    MergedTitles = Table.NestedJoin(StandardizedGenreName, {"netflix_id"}, Dim_Titles, {"netflix_id"}, "Dim_Titles", JoinKind.Inner),
				    ExpandedTitleKey = Table.ExpandTableColumn(MergedTitles, "Dim_Titles", {"title_key"}, {"title_key"}),
				
				    MergedGenres = Table.NestedJoin(ExpandedTitleKey, {"genre_name_clean"}, Dim_Genres, {"genre_name"}, "Dim_Genres", JoinKind.Inner),
				    ExpandedGenreKey = Table.ExpandTableColumn(MergedGenres, "Dim_Genres", {"genre_key"}, {"genre_key"}),
				
				    SelectFinal = Table.SelectColumns(ExpandedGenreKey, {"title_key", "genre_key"}),
				    AddWeight = Table.AddColumn(SelectFinal, "genre_weight", each 1.0, type number),
				    Deduplicated = Table.Distinct(AddWeight)
				in
				    Deduplicated

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

