table Dim_Date
	lineageTag: c795c4fb-3458-413e-92c4-1dea7e693c7a

	column full_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: fe9bd168-fa42-4a6c-a753-b915c4e8daa4
		summarizeBy: none
		sourceColumn: full_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 9b4368e5-2e30-4532-8d10-e2e8c184950d
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 4db19a2c-d05b-4dd5-876c-f1bff978e651
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: fec3cfdd-5ab9-4457-9314-b123247812d8
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column quarter_name
		dataType: string
		lineageTag: 7951bee3-8798-4754-be6d-4ebbd70863e7
		summarizeBy: none
		sourceColumn: quarter_name

		annotation SummarizationSetBy = Automatic

	column month_number
		dataType: int64
		formatString: 0
		lineageTag: 56b66afa-a136-4170-b9c6-979b80dcf0b3
		summarizeBy: sum
		sourceColumn: month_number

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 56946eac-df82-44d8-a1ff-28750f37207e
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column month_short
		dataType: string
		lineageTag: 4141d28f-00d7-4c94-8302-3488a4ae99e5
		summarizeBy: none
		sourceColumn: month_short

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: d0b4824e-3f3b-4a4f-bd1c-a3b149ab88bd
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 293c8420-6593-4169-8001-5114daa83810
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8360d836-0cf0-4abb-afee-b149e674a971
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column fiscal_period
		dataType: string
		lineageTag: 81aadce6-8dcb-42ef-a40c-c839b858f119
		summarizeBy: none
		sourceColumn: fiscal_period

		annotation SummarizationSetBy = Automatic

	column is_current_year
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e90ee879-da9f-442b-b30f-edd4522f6e65
		summarizeBy: none
		sourceColumn: is_current_year

		annotation SummarizationSetBy = Automatic

	column is_past_or_current
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c43800cd-1580-496e-ab60-b03fdc233b65
		summarizeBy: none
		sourceColumn: is_past_or_current

		annotation SummarizationSetBy = Automatic

	column relative_year_offset
		dataType: int64
		formatString: 0
		lineageTag: 68f30b2c-03d7-43fa-a216-ef1c441aab37
		summarizeBy: sum
		sourceColumn: relative_year_offset

		annotation SummarizationSetBy = Automatic

	column relative_month_offset
		dataType: int64
		formatString: 0
		lineageTag: 2444ade7-80c7-4ae3-9056-7efda7b01a25
		summarizeBy: sum
		sourceColumn: relative_month_offset

		annotation SummarizationSetBy = Automatic

	column is_netflix_quarter_end
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 036f2d7e-cb91-4ee0-8cd1-500d25c7bde5
		summarizeBy: none
		sourceColumn: is_netflix_quarter_end

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				    // 1. Dynamically fetch all dates from Dim_Titles
				    DatasetDates = List.RemoveNulls(Dim_Titles[netflix_date_added_clean]),
				
				    // 2. Compute dynamic Min and Max dates with fallback defaults
				    MinDateRaw = if List.IsEmpty(DatasetDates) then #date(2020, 1, 1) else List.Min(DatasetDates),
				    MaxDateRaw = if List.IsEmpty(DatasetDates) then #date(2026, 12, 31) else List.Max(DatasetDates),
				    CurrentDate = DateTime.Date(DateTime.LocalNow()),
				
				    // 3. Expand boundaries to full calendar years
				    StartYear = Date.Year(MinDateRaw),
				    EndYear = Date.Year(List.Max({MaxDateRaw, CurrentDate})),
				    StartDate = #date(StartYear, 1, 1),
				    EndDate = #date(EndYear, 12, 31),
				
				    // 4. Generate continuous daily dates list
				    NumberOfDays = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, NumberOfDays, #duration(1, 0, 0, 0)),
				    DateTable = Table.FromList(DateList, Splitter.SplitByNothing(), {"full_date"}, null, ExtraValues.Error),
				    TypedDate = Table.TransformColumnTypes(DateTable, {{"full_date", type date}}),
				
				    // 5. Standard Calendar Attributes
				    AddDateKey = Table.AddColumn(TypedDate, "date_key", each Date.Year([full_date]) * 10000 + Date.Month([full_date]) * 100 + Date.Day([full_date]), Int64.Type),
				    AddYear = Table.AddColumn(AddDateKey, "year", each Date.Year([full_date]), Int64.Type),
				    AddQuarter = Table.AddColumn(AddYear, "quarter", each Date.QuarterOfYear([full_date]), Int64.Type),
				    AddQuarterName = Table.AddColumn(AddQuarter, "quarter_name", each "Q" & Text.From([quarter]) & " " & Text.From([year]), type text),
				    AddMonthNum = Table.AddColumn(AddQuarterName, "month_number", each Date.Month([full_date]), Int64.Type),
				    AddMonthName = Table.AddColumn(AddMonthNum, "month_name", each Date.MonthName([full_date]), type text),
				    AddMonthShort = Table.AddColumn(AddMonthName, "month_short", each Text.Start([month_name], 3), type text),
				    AddDayOfWeek = Table.AddColumn(AddMonthShort, "day_of_week", each Date.DayOfWeek([full_date], Day.Monday) + 1, Int64.Type),
				    AddDayName = Table.AddColumn(AddDayOfWeek, "day_name", each Date.DayOfWeekName([full_date]), type text),
				    AddIsWeekend = Table.AddColumn(AddDayName, "is_weekend", each if [day_of_week] >= 6 then true else false, type logical),
				    AddFiscalPeriod = Table.AddColumn(AddIsWeekend, "fiscal_period", each "FY" & Text.From([year]) & "-Q" & Text.From([quarter]), type text),
				
				    // 6. Dynamic Streaming & Time-Intelligence Offsets
				    AddIsCurrentYear = Table.AddColumn(AddFiscalPeriod, "is_current_year", each Date.Year([full_date]) = Date.Year(CurrentDate), type logical),
				    AddIsPastOrCurrent = Table.AddColumn(AddIsCurrentYear, "is_past_or_current", each [full_date] <= CurrentDate, type logical),
				    AddYearOffset = Table.AddColumn(AddIsPastOrCurrent, "relative_year_offset", each Date.Year([full_date]) - Date.Year(CurrentDate), Int64.Type),
				    AddMonthOffset = Table.AddColumn(AddYearOffset, "relative_month_offset", each 
				        ((Date.Year([full_date]) - Date.Year(CurrentDate)) * 12) + (Date.Month([full_date]) - Date.Month(CurrentDate)),
				        Int64.Type
				    ),
				    AddNetflixQuarterEnd = Table.AddColumn(AddMonthOffset, "is_netflix_quarter_end", each 
				        (Date.Month([full_date]) = 3 and Date.Day([full_date]) = 31) or
				        (Date.Month([full_date]) = 6 and Date.Day([full_date]) = 30) or
				        (Date.Month([full_date]) = 9 and Date.Day([full_date]) = 30) or
				        (Date.Month([full_date]) = 12 and Date.Day([full_date]) = 31),
				        type logical
				    )
				in
				    AddNetflixQuarterEnd
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

