table Dim_Date
	lineageTag: c011dcb7-54c8-483f-872a-c2f6d7cafd4c

	column full_date
		dataType: dateTime
		formatString: d mmmm yyyy
		lineageTag: bbc1f624-9e80-4a9e-80f3-ae5ccd16cadf
		summarizeBy: none
		sourceColumn: full_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: c5af374a-1bb4-4df2-ad78-d6b124d4a8c8
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: b02c64e9-d6ba-4fa1-85d4-66519602cae8
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 0f3a4118-2dea-42ff-b74a-35758e16f806
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column quarter_name
		dataType: string
		lineageTag: ec29caa5-2c69-4a31-81b3-0d7c64c7f864
		summarizeBy: none
		sourceColumn: quarter_name
		sortByColumn: quarter

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column month_number
		dataType: int64
		formatString: 0
		lineageTag: b65e947f-f29a-4f97-bc3d-8869e216f9ed
		summarizeBy: sum
		sourceColumn: month_number

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: db3a6e81-4e7f-465b-823c-15a0aab58db3
		summarizeBy: none
		sourceColumn: month_name

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column month_short
		dataType: string
		lineageTag: 8a7ba997-9f9b-4e58-b661-6488c5d649de
		summarizeBy: none
		sourceColumn: month_short
		sortByColumn: month_number

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: 3d55c301-5a81-4030-a65f-79eb9557dbcd
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: e8f88538-eb1b-428f-9e7b-c6b01d49b684
		summarizeBy: none
		sourceColumn: day_name
		sortByColumn: day_of_week

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 52b9f9c6-76bd-442d-8270-5ed23e1c25fe
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column fiscal_period
		dataType: string
		lineageTag: dd1bdc5f-8715-4386-a360-d9dc17e23b28
		summarizeBy: none
		sourceColumn: fiscal_period

		annotation SummarizationSetBy = Automatic

	column is_current_year
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7a0be934-beed-4b08-8bc2-bdb735e128c7
		summarizeBy: none
		sourceColumn: is_current_year

		annotation SummarizationSetBy = Automatic

	column is_past_or_current
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a4759d47-25a3-4271-9f8a-6c5e50715137
		summarizeBy: none
		sourceColumn: is_past_or_current

		annotation SummarizationSetBy = Automatic

	column relative_year_offset
		dataType: int64
		formatString: 0
		lineageTag: d07d2129-0b0c-4b38-8048-c429fce3bdcf
		summarizeBy: sum
		sourceColumn: relative_year_offset

		annotation SummarizationSetBy = Automatic

	column relative_month_offset
		dataType: int64
		formatString: 0
		lineageTag: f3dc4239-6653-4616-ba19-22e5f9d04aa2
		summarizeBy: sum
		sourceColumn: relative_month_offset

		annotation SummarizationSetBy = Automatic

	column is_netflix_quarter_end
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 46479f5d-ecf2-42ac-b0f5-0eabb1ce9cf8
		summarizeBy: none
		sourceColumn: is_netflix_quarter_end

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				    DatasetDates = List.RemoveNulls(Dim_Titles[netflix_date_added_clean]),
				    MinDateRaw = if List.IsEmpty(DatasetDates) then #date(2015, 1, 1) else List.Min(DatasetDates),
				    MaxDateRaw = if List.IsEmpty(DatasetDates) then #date(2026, 12, 31) else List.Max(DatasetDates),
				    CurrentDate = DateTime.Date(DateTime.LocalNow()),
				
				    StartYear = Date.Year(MinDateRaw),
				    EndYear = Date.Year(List.Max({MaxDateRaw, CurrentDate})),
				    StartDate = #date(StartYear, 1, 1),
				    EndDate = #date(EndYear, 12, 31),
				
				    NumberOfDays = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, NumberOfDays, #duration(1, 0, 0, 0)),
				    DateTable = Table.FromList(DateList, Splitter.SplitByNothing(), {"full_date"}, null, ExtraValues.Error),
				    TypedDate = Table.TransformColumnTypes(DateTable, {{"full_date", type date}}),
				
				    AddDateKey = Table.AddColumn(TypedDate, "date_key", each Date.Year([full_date]) * 10000 + Date.Month([full_date]) * 100 + Date.Day([full_date]), Int64.Type),
				    AddYear = Table.AddColumn(AddDateKey, "year", each Date.Year([full_date]), Int64.Type),
				    AddQuarter = Table.AddColumn(AddYear, "quarter", each Date.QuarterOfYear([full_date]), Int64.Type),
				    AddQuarterName = Table.AddColumn(AddQuarter, "quarter_name", each "Q" & Text.From([quarter]) & " " & Text.From([year]), type text),
				    AddMonthNum = Table.AddColumn(AddQuarterName, "month_number", each Date.Month([full_date]), Int64.Type),
				    AddMonthName = Table.AddColumn(AddMonthNum, "month_name", each Date.MonthName([full_date]), type text),
				    AddMonthShort = Table.AddColumn(AddMonthName, "month_short", each Text.Start([month_name], 3), type text),
				    AddDayOfWeek = Table.AddColumn(AddMonthShort, "day_of_week", each Date.DayOfWeek([full_date], Day.Monday) + 1, Int64.Type),
				    AddDayName = Table.AddColumn(AddDayOfWeek, "day_name", each Date.DayOfWeekName([full_date]), type text),
				    AddIsWeekend = Table.AddColumn(AddDayName, "is_weekend", each if [day_of_week] <> null and [day_of_week] >= 6 then true else false, type logical),
				    AddFiscalPeriod = Table.AddColumn(AddIsWeekend, "fiscal_period", each "FY" & Text.From(try [year] otherwise 2026) & "-Q" & Text.From(try [quarter] otherwise 1), type text),
				    AddIsCurrentYear = Table.AddColumn(AddFiscalPeriod, "is_current_year", each if [full_date] <> null then Date.Year([full_date]) = Date.Year(CurrentDate) else false, type logical),
				    AddIsPastOrCurrent = Table.AddColumn(AddIsCurrentYear, "is_past_or_current", each if [full_date] <> null then [full_date] <= CurrentDate else false, type logical),
				    AddYearOffset = Table.AddColumn(AddIsPastOrCurrent, "relative_year_offset", each if [full_date] <> null then Date.Year([full_date]) - Date.Year(CurrentDate) else 0, Int64.Type),
				    AddMonthOffset = Table.AddColumn(AddYearOffset, "relative_month_offset", each 
				        if [full_date] <> null then
				            ((Date.Year([full_date]) - Date.Year(CurrentDate)) * 12) + (Date.Month([full_date]) - Date.Month(CurrentDate))
				        else 0,
				        Int64.Type
				    ),
				    AddNetflixQuarterEnd = Table.AddColumn(AddMonthOffset, "is_netflix_quarter_end", each 
				        if [full_date] <> null then
				            (Date.Month([full_date]) = 3 and Date.Day([full_date]) = 31) or
				            (Date.Month([full_date]) = 6 and Date.Day([full_date]) = 30) or
				            (Date.Month([full_date]) = 9 and Date.Day([full_date]) = 30) or
				            (Date.Month([full_date]) = 12 and Date.Day([full_date]) = 31)
				        else false,
				        type logical
				    )
				in
				    AddNetflixQuarterEnd
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

