table Dim_Titles
	lineageTag: 3c6eb7fa-f635-4244-87ec-cd841fdf882e

	column netflix_id
		dataType: string
		lineageTag: 8dd9314b-78a6-4b8c-a521-dbf7ad1bc2d1
		summarizeBy: none
		sourceColumn: netflix_id

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: d09bdabf-9aad-421a-92b5-0136b7a556bc
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column title_type
		dataType: string
		lineageTag: 9b7d5d0c-38c1-4ac1-9a6d-aca9c1948802
		summarizeBy: none
		sourceColumn: title_type

		annotation SummarizationSetBy = Automatic

	column release_year
		dataType: double
		lineageTag: c193dbf5-e902-4ab6-859f-14d92b34a699
		summarizeBy: sum
		sourceColumn: release_year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column netflix_date_added_clean
		dataType: dateTime
		formatString: Long Date
		lineageTag: eff44351-8afc-49ce-aa26-d7d48ef2e8ae
		summarizeBy: none
		sourceColumn: netflix_date_added_clean

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column runtime_minutes_clean
		dataType: int64
		formatString: 0
		lineageTag: 24db88b4-9dc6-4256-8a20-df0f1f369654
		summarizeBy: sum
		sourceColumn: runtime_minutes_clean

		annotation SummarizationSetBy = Automatic

	column maturity_rating
		dataType: string
		lineageTag: 9e581131-722b-423a-abec-679eb8e33f9b
		summarizeBy: none
		sourceColumn: maturity_rating

		annotation SummarizationSetBy = Automatic

	column title_key
		dataType: int64
		formatString: 0
		lineageTag: 68f4af35-640d-4a95-9740-90a8af40238d
		summarizeBy: none
		sourceColumn: title_key

		annotation SummarizationSetBy = Automatic

	column catalog_era
		dataType: string
		lineageTag: 1545a122-d232-4c13-baef-a04e32b508c3
		summarizeBy: none
		sourceColumn: catalog_era

		annotation SummarizationSetBy = Automatic

	column runtime_tier
		dataType: string
		lineageTag: fa00b519-d7b0-4dcd-a67a-7fc7243f6a78
		summarizeBy: none
		sourceColumn: runtime_tier

		annotation SummarizationSetBy = Automatic

	column maturity_category
		dataType: string
		lineageTag: a7125166-da00-481c-93cd-68af08689f5c
		summarizeBy: none
		sourceColumn: maturity_category

		annotation SummarizationSetBy = Automatic

	partition Dim_Titles = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    // Part A: Extract & Clean Live 2026 Scraped Releases
				    SourceLive = try PostgreSQL.Database("localhost:5432", "streampulse") otherwise null,
				    stg_data = if SourceLive <> null then SourceLive{[Schema="staging", Item="stg_netflix_titles"]}[Data] else #table({"netflix_id","title","title_type","release_year","date_added","runtime_seconds","maturity_rating"}, {}),
				
				    ScrubLive = Table.TransformColumns(stg_data, {
				        {"title", each Text.Proper(Text.Trim(Text.Replace(Text.From(_), Character.FromNumber(160), " "))), type text},
				        {"netflix_id", each Text.Trim(Text.From(_)), type text}
				    }),
				
				    AddCleanDateLive = Table.AddColumn(ScrubLive, "netflix_date_added_clean", each
				        try Date.From(DateTimeZone.From([date_added]))
				        otherwise try Date.FromText([date_added], "en-US")
				        otherwise try Date.FromText([date_added], "en-GB")
				        otherwise #date(2026, 1, 1),
				        type date
				    ),
				
				    AddCleanRuntimeLive = Table.AddColumn(AddCleanDateLive, "runtime_minutes_clean", each
				        let
				            txt = if [runtime_seconds] = null then "" else Text.Lower(Text.From([runtime_seconds])),
				            mins = if Text.Contains(txt, "mins") or Text.Contains(txt, "min") then
				                       Number.From(Text.Select(txt, {"0".."9"}))
				                   else if Text.Contains(txt, "h") then
				                       let
				                           parts = Text.Split(txt, "h"),
				                           hours = Number.From(Text.Select(parts{0}, {"0".."9"})),
				                           rem_mins = Number.From(Text.Select(parts{1}, {"0".."9"}))
				                       in
				                           (hours * 60) + rem_mins
				                   else if try Number.FromText(txt) > 500 otherwise false then
				                       Number.Round(Number.FromText(txt) / 60)
				                   else
				                       try Number.FromText(txt) otherwise 90
				        in
				            if mins = null or mins <= 0 then 90 else mins,
				        Int64.Type
				    ),
				
				    CleanRatingLive = Table.TransformColumns(AddCleanRuntimeLive, {
				        {"maturity_rating", each if _ = null then "TV-MA" else Text.Upper(Text.Trim(Text.Replace(Text.From(_), " ", "-"))), type text}
				    }),
				
				    SelectLiveCols = Table.SelectColumns(CleanRatingLive, {
				        "netflix_id", "title", "title_type", "release_year", "netflix_date_added_clean", "runtime_minutes_clean", "maturity_rating"
				    }),
				
				    // Part B: Extract & Clean 7,786 Historical Kaggle Benchmark Records
				    SourceHist = Csv.Document(File.Contents(File_Path & "netflix_enriched_historical.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeadersHist = Table.PromoteHeaders(SourceHist, [PromoteAllScalars=true]),
				
				    ScrubHist = Table.TransformColumns(PromotedHeadersHist, {
				        {"id", each Text.Trim(Text.From(_)), type text},
				        {"title", each Text.Proper(Text.Trim(Text.Replace(Text.From(_), Character.FromNumber(160), " "))), type text},
				        {"type", each if _ = null then "Movie" else if Text.Upper(Text.From(_)) = "MOVIE" then "Movie" else "TV Show", type text},
				        {"release_year", each try Number.FromText(Text.From(_)) otherwise 2020, Int64.Type},
				        {"runtime", each try Number.FromText(Text.From(_)) otherwise 90, Int64.Type},
				        {"age_certification", each if _ = null or Text.From(_) = "" then "TV-MA" else Text.Upper(Text.Trim(Text.From(_))), type text}
				    }),
				
				    AddCleanDateHist = Table.AddColumn(ScrubHist, "netflix_date_added_clean", each
				        let
				            y = try Int64.From([release_year]) otherwise 2020,
				            valid_y = if y = null or y < 1900 or y > 2100 then 2020 else y
				        in
				            #date(valid_y, 1, 1),
				        type date
				    ),
				
				    RenameHist = Table.RenameColumns(AddCleanDateHist, {
				        {"id", "netflix_id"},
				        {"type", "title_type"},
				        {"runtime", "runtime_minutes_clean"},
				        {"age_certification", "maturity_rating"}
				    }),
				
				    SelectHistCols = Table.SelectColumns(RenameHist, {
				        "netflix_id", "title", "title_type", "release_year", "netflix_date_added_clean", "runtime_minutes_clean", "maturity_rating"
				    }),
				
				    // Part C: Combine & Enrich Conformed Title Attributes (100% Null-Safe)
				    Combined = Table.Combine({SelectLiveCols, SelectHistCols}),
				    Deduplicated = Table.Distinct(Combined, {"netflix_id"}),
				    AddTitleKey = Table.AddIndexColumn(Deduplicated, "title_key", 1, 1, Int64.Type),
				
				    AddEra = Table.AddColumn(AddTitleKey, "catalog_era", each
				        let
				            y = if [release_year] = null then 2020 else [release_year]
				        in
				            if y = 2026 then "2026 Live Releases"
				            else if y >= 2024 then "2024-2025 Modern"
				            else if y >= 2015 then "2015-2023 Streaming Boom"
				            else "Historical Archive (<2015)",
				        type text
				    ),
				
				    AddRuntimeTier = Table.AddColumn(AddEra, "runtime_tier", each
				        let
				            t = if [title_type] = null then "Movie" else Text.Proper(Text.Trim(Text.From([title_type]))),
				            mins = if [runtime_minutes_clean] = null then 90 else [runtime_minutes_clean]
				        in
				            if t = "TV Show" then "Episodic Series"
				            else if mins < 45 then "Short Feature (<45m)"
				            else if mins <= 100 then "Standard Feature (45-100m)"
				            else if mins <= 140 then "Extended Feature (101-140m)"
				            else "Blockbuster Epic (>140m)",
				        type text
				    ),
				
				    AddMaturityCategory = Table.AddColumn(AddRuntimeTier, "maturity_category", each
				        let
				            r = if [maturity_rating] = null then "TV-MA" else Text.Upper(Text.Trim(Text.From([maturity_rating])))
				        in
				            if r = "TV-MA" or r = "R" or r = "NC-17" then "Adult / Mature (18+)"
				            else if r = "TV-14" or r = "PG-13" then "Teens & Young Adults (13+)"
				            else if r = "PG" or r = "TV-PG" then "Parental Guidance (PG)"
				            else "Kids & Family (G / TV-Y)",
				        type text
				    )
				in
				    AddMaturityCategory

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

