table Fact_Streaming_Performance
	lineageTag: c8734d91-57c8-499c-ab38-6f9bcf0a77f5

	column title_key
		dataType: int64
		formatString: 0
		lineageTag: b782af71-f8af-4818-9932-0a38427f97d8
		summarizeBy: none
		sourceColumn: title_key

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 0a7ba4b8-a0f4-4aaa-bf0d-e16a465dae68
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column territory_key
		dataType: int64
		formatString: 0
		lineageTag: e5934b79-287a-4b52-8ebb-13ccdb0e212b
		summarizeBy: none
		sourceColumn: territory_key

		annotation SummarizationSetBy = Automatic

	column device_category
		dataType: string
		lineageTag: b2d7a204-997d-4530-adfa-02d3c3453926
		summarizeBy: none
		sourceColumn: device_category

		annotation SummarizationSetBy = Automatic

	column global_view_hours_millions
		dataType: double
		lineageTag: 1e1cc882-5cea-4fd5-9143-e62e9a2b20cd
		summarizeBy: sum
		sourceColumn: global_view_hours_millions

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_completion_pct
		dataType: double
		lineageTag: aa95e871-8f17-4429-916f-f0f6cfdb5bad
		summarizeBy: sum
		sourceColumn: avg_completion_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column subscribers_reached_thousands
		dataType: int64
		formatString: 0
		lineageTag: 9ae5b1b3-70af-4c21-9241-0d005a64269c
		summarizeBy: sum
		sourceColumn: subscribers_reached_thousands

		annotation SummarizationSetBy = Automatic

	column performance_key
		dataType: int64
		formatString: 0
		lineageTag: df8804b8-4eb5-4729-8d9a-03d9fdeccc39
		summarizeBy: sum
		sourceColumn: performance_key

		annotation SummarizationSetBy = Automatic

	partition Fact_Streaming_Performance = m
		mode: import
		queryGroup: Facts
		source =
				let
				    Source = Parquet.Document(File.Contents(File_Path & "streaming_viewership_wide.parquet")),
				
				    Unpivoted = Table.Unpivot(Source, {"Hours_2026_01", "Hours_2026_02", "Hours_2026_03"}, "Month_Col", "global_view_hours_millions"),
				    CleanHours = Table.TransformColumns(Unpivoted, {{"global_view_hours_millions", each if _ = null then 0.0 else if _ < 0 then 0.0 else _, type number}}),
				
				    AddDateKey = Table.AddColumn(CleanHours, "date_key", each
				        let
				            m_str = Text.AfterDelimiter([Month_Col], "Hours_"),
				            y = Number.FromText(Text.Start(m_str, 4)),
				            m = Number.FromText(Text.End(m_str, 2))
				        in
				            y * 10000 + m * 100 + 1,
				        Int64.Type
				    ),
				
				    AddTerritoryKey = Table.AddColumn(AddDateKey, "territory_key", each
				        let c = Text.Upper(Text.Trim(Text.From([territory_region]))) in
				        if c = "USA" or c = "US" or c = "UNITED STATES" then 1
				        else if c = "UK" or c = "GBR" or c = "GREAT BRITAIN" then 2
				        else if c = "KOR" or c = "SOUTH KOREA" then 3
				        else if c = "JPN" or c = "JAPAN" then 4
				        else 5,
				        Int64.Type
				    ),
				
				    MergedTitles = Table.NestedJoin(AddTerritoryKey, {"catalog_ref_id"}, Dim_Titles, {"netflix_id"}, "Dim_Titles", JoinKind.Inner),
				    ExpandedTitleKey = Table.ExpandTableColumn(MergedTitles, "Dim_Titles", {"title_key"}, {"title_key"}),
				
				    SelectFact = Table.SelectColumns(ExpandedTitleKey, {
				        "title_key", "date_key", "territory_key", "device_category",
				        "global_view_hours_millions", "avg_completion_pct", "subscribers_reached_thousands"
				    }),
				    AddPerformanceKey = Table.AddIndexColumn(SelectFact, "performance_key", 1, 1, Int64.Type)
				in
				    AddPerformanceKey

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

